spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/playground_test
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
